# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_bleach.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=40)),
                ('link', models.URLField(max_length=2083)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('content', django_bleach.models.BleachField()),
                ('updated', models.DateTimeField(blank=True)),
                ('published', models.DateTimeField(db_index=True)),
                ('added_to_subscribers', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'get_latest_by': 'published',
                'verbose_name_plural': 'entries',
                'ordering': ('-published', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('description', django_bleach.models.BleachField(blank=True)),
                ('icon', models.URLField(blank=True)),
                ('site_url', models.URLField(blank=True)),
                ('feed_url', models.URLField(unique=True)),
                ('disabled', models.BooleanField(db_index=True, default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('next_checked', models.DateTimeField(blank=True, null=True)),
                ('check_frequency', models.PositiveSmallIntegerField(choices=[(1, 'Every Hour'), (12, 'Every 12 Hours'), (24, 'Every Day')], default=1)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('has_subscribers', models.BooleanField(default=False)),
                ('has_new_feeds', models.BooleanField(db_index=True, default=True)),
                ('subscriptions', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('headers', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('entries', models.PositiveIntegerField(default=0)),
                ('feed', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='reader.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('u', 'Unread'), ('r', 'Read'), ('s', 'Saved')], default='u', max_length=1)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Entry')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Feed'),
        ),
    ]
