# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='has_new_feeds',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
