# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20160521_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedlog',
            options={'verbose_name': 'Feed Log', 'verbose_name_plural': 'Feed Logs'},
        ),
        migrations.AlterModelOptions(
            name='userentry',
            options={'verbose_name': 'User Entry', 'verbose_name_plural': 'User Entries'},
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='has_new_feeds',
            new_name='has_new_entries',
        ),
    ]
